# file per il collegamento con il db

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/RankUpDB
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update